[package]
name = "mozart"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["rt", "macros"] }
uuid = { version = "1.10.0", features = ["fast-rng"] }
