[package]
name = "mozart"
version = "0.1.0"
edition = "2021"

[features]
default = ["haskell"]
haskell = []

[dependencies]
axum = "0.7.7"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"
time = "0.3.36"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
uuid = { version = "1.10.0", features = ["fast-rng", "v4"] }

[dev-dependencies]
tower = { version = "0.5.1", features = ["util"] }
